sonar.projectKey=natsnts_api-academia-treino
sonar.organization=natsnts

sonar.exclusions=venv/**,.venv/**,**/__pycache__/**,**/*.pyc

sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.11