sonar.projectKey=natsnts_api-academia-treino
sonar.organization=natsnts

sonar.sources=app
sonar.tests=tests

sonar.exclusions=venv/**,.venv/**,**/__pycache__/**,**/*.pyc

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml